// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'post.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'post.g.dart';

@freezed
class Post with _$Post {
  const factory Post({
    required String uid,
    required String postId,
    required String postMusicImg,
    required String postMusicArtistName,
    required String postMusicName,
    required String postMsg,
    required DateTime postTimestamp,
    required String postMusicSpotifyUrl,
    required String postMusicPreviewUrl,
    required int postLikeCount,
  }) = _Post;

  factory Post.fromJson(Map<String, Object?> json) => _$PostFromJson(json);
}
