// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'following_user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'following_user.g.dart';

@freezed
class FollowingUser with _$FollowingUser {
  const factory FollowingUser({
    required String uid,
    required String followingUserId,
  }) = _FollowingUser;

  factory FollowingUser.fromJson(Map<String, Object?> json) =>
      _$FollowingUserFromJson(json);
}
