// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'followed_user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'followed_user.g.dart';

@freezed
class FollowedUser with _$FollowedUser {
  const factory FollowedUser({
    required String uid, //フォローする人のuid
    required String followedUid, //フォローされる人のuid
  }) = _FollowedUser;

  factory FollowedUser.fromJson(Map<String, Object?> json) =>
      _$FollowedUserFromJson(json);
}
