// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'spotify_track.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'spotify_track.g.dart';

@freezed
class SpotifyTrack with _$SpotifyTrack {
  const factory SpotifyTrack({
    required String trackImg,
    required String artistName,
    required String trackName,
    required String trackExternalUrl,
    required String? previewUrl,
  }) = _SpotifyTrack;

  factory SpotifyTrack.fromJson(Map<String, Object?> json) =>
      _$SpotifyTrackFromJson(json);
}
