// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'quiz_choice.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'quiz_choice.g.dart';

@freezed
class QuizChoice with _$QuizChoice {
  const factory QuizChoice({
    required String quizChoiceUid,
    required String quizChoiceUserName,
    required String quizChoiceUserImg,
  }) = _QuizChoice;

  factory QuizChoice.fromJson(Map<String, Object?> json) =>
      _$QuizChoiceFromJson(json);
}
