// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'item.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'item.g.dart';

@freezed
class Item with _$Item {
  const factory Item({
    required String uid,
    required String itemId,
    required bool isSaled,
    required String artistSpotifyId,
    required String artistName,
    required String artistSpotifyUrl,
    required List<String> itemImgs,
    required String itemName,
    required String itemDescription,
    required int price,
    required String size,
    required String categories,
  }) = _Item;

  factory Item.fromJson(Map<String, Object?> json) => _$ItemFromJson(json);
}
