// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'community.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'community.g.dart';

@freezed
class Community with _$Community {
  const factory Community({
    required String communityId,
    required String communityName,
    required List<String> communityMemberUids,
  }) = _Community;

  factory Community.fromJson(Map<String, Object?> json) =>
      _$CommunityFromJson(json);
}
